### ISSUE TITLE
Tests fail for Node 10

### ISSUE THREAD

**Issue by ianwsperber** [FormidableLabs/yesno#52]
Tests are failing in CI for Node 10. This is occurring for commits that previously succeeded, so is likely due to a change either in Node or the request libraries.

Example:

https://travis-ci.com/FormidableLabs/yesno/jobs/183919449

```
  18) Yesno
       #mock
         should accept an optional comparatorFn, which can accept a mock when it does not throw:
     RequestError: TypeError: Cannot set property 'clientRequest' of undefined
      at new RequestError (node_modules/request-promise-core/lib/errors.js:14:15)
      at Request.plumbing.callback (node_modules/request-promise-core/lib/plumbing.js:87:29)
      at Request.RP$callback [as _callback] (node_modules/request-promise-core/lib/plumbing.js:46:31)
      at self.callback (node_modules/request/request.js:185:22)
      at Request.start (node_modules/request/request.js:753:10)
      at Request.end (node_modules/request/request.js:1511:10)
      at end (node_modules/request/request.js:564:14)
      at Immediate._onImmediate (node_modules/request/request.js:578:7)
```

**Comment by keithcom** [comment]
Unable to reproduce on latest node v10. I am seeing errors in the integration test on latest node v12, but will address in a separate ticket.
