### ISSUE TITLE
Integration tests failing in node v12

### ISSUE THREAD

**Issue by keithcom** [FormidableLabs/yesno#70]
set node version to v12.18 (also fails in v12.3 and probably all of v12)
run 'yarn tests'
see integration test errors

```
  yesno
    ✓ should send get to test server
    ✓ should proxy HTTP GET requests (485ms)
    1) should proxy HTTP POST requests
    2) should mock HTTPS requests
    #save
      - should create records locally
    #intercepted
      ✓ should allow querying for the various requests made
      ✓ should treat JSON request or response bodies as objects
    #redact
      ✓ should allow redacting a single nested property
    mock mode
      ✓ should play back the requests from disk


  6 passing (11s)
  1 pending
  2 failing

  1) yesno
       should proxy HTTP POST requests:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/keith/Formidable/yesno/test/integration/yesno.spec.ts)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

  2) yesno
       should mock HTTPS requests:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/keith/Formidable/yesno/test/integration/yesno.spec.ts)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)



npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! yesno-http@0.0.7 integration: `mocha --timeout 5000 "test/integration/**/*.spec.ts"`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the yesno-http@0.0.7 integration script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/keith/.npm/_logs/2020-06-12T16_38_16_098Z-debug.log
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by kevinmstephens** [comment]
Opened a ticket in node-mitm lib about this https://github.com/moll/node-mitm/issues/67

**Comment by gstilman** [comment]
FYI this seems to affect all node versions >12. Sporadically, it will work but mostly times out.

I was able to record tests using node v10.16.3
